"""Client for authentication endpoints (login, logout, refresh, register)."""

# from .base_client import BaseClient
#
# class AuthClient(BaseClient):
#     def login(self, username, password): ...
#     def refresh(self, token): ...
#     def logout(self): ...
