"""Client for user management endpoints (CRUD, roles, permissions)."""

# from .base_client import BaseClient
#
# class UsersClient(BaseClient):
#     def create_user(self, payload): ...
#     def get_user(self, user_id): ...
#     def delete_user(self, user_id): ...
